// frontend/src/components/Post/index.tsx
import { Bookmark, BookmarkBorder, Favorite, FavoriteBorder, MoreHoriz } from "@styled-icons/material-rounded";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import styled, { css } from "styled-components"
import { IPost } from "../../../../shared/types";
import { usePostStore } from "../../store/postStore";
import { useUserStore } from "../../store/userStore";

const Wrapper = styled.div`
  padding: 1rem 0;
  border-bottom: 1px solid #000000;

  &:last-child {
    border-bottom: 0;
  }
`;

const Top = styled.div`
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
`;

const Mid = styled.div`
  padding: 0 0 0.25rem 1rem;
  white-space: pre-wrap;
  word-break: break-word;
`;

const Bottom = styled.div`
  display: flex;
  align-items: center;
  padding-left: 1rem;
`;

const TopWrapper = styled.div`
  display: flex;
  flex-direction: row;
`;

const UserInfo = styled.div`
  cursor: pointer;

  display: grid;
  grid-template-columns: auto auto auto;
  margin-bottom: 1px;

  &:hover {
    border-bottom: 1px solid #000000;
    margin-bottom: 0;
  }
`;

const overflowEllipsis = css`
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
`;

const Username = styled.div`
  ${overflowEllipsis}
  padding-right: 0.25rem;
`;

const Usertag = styled.div`
  ${overflowEllipsis}
`;

const Date = styled.div`
  margin: 0 0.25rem;
  white-space: nowrap;
`;

const Text = styled.span`
  margin-right: 0.25rem;
`;

const Icon = styled.button`
  cursor: pointer;
  width: 32px;
  height: 32px;
`;

function Post({ post }: { post: IPost }) {
  const fetchUserById = useUserStore(state => state.fetchUserById);
  const user = useUserStore(state => state.getUserById(post.userId));

  const like = usePostStore(state => state.likePost)
  const bookmark = usePostStore(state => state.bookmarkPost)
  const deletePost = usePostStore(state => state.deletePost);

  const doLike = () => like(post);
  const doBookmark = () => bookmark(post);
  const doDelete = () => deletePost(post);

  const navigate = useNavigate();
  const gotoUser = () => navigate(`/user/${user?.tag}`)

  useEffect(() => { if (!user) fetchUserById(post.userId) }, []);

  if (!user) return null;

  return (
    <Wrapper>
      <Top>
        <TopWrapper>
          <UserInfo onClick={gotoUser}>
            <Username>{user.name}</Username>
            <span>@</span>
            <Usertag>{user.tag}</Usertag>
          </UserInfo>
          <Date>2 hours ago</Date>
        </TopWrapper>
        <Icon as={MoreHoriz} onClick={doDelete} />
      </Top>
      <Mid>{post.content}</Mid>
      <Bottom>
        <Text>{post.likeCount}</Text>
        <Icon as={post.liked ? Favorite : FavoriteBorder} onClick={doLike} />
        <Icon as={post.bookmarked ? Bookmark : BookmarkBorder} onClick={doBookmark} />
      </Bottom>
    </Wrapper>
  )
}

export default Post

// frontend/src/components/Post.vue
<script lang="ts" setup>
import HeartIcon from "./Icons/HeartIcon.vue";
import BookmarkIcon from "./Icons/BookmarkIcon.vue";
import type { IPost, IUser } from "../../../shared/types";
import { usePosts } from "@/stores/posts";
import router from "@/router";
import { ref } from "vue";
import { useUsers } from "@/stores/users";
import { date } from "@/util/date";
import MoreIcon from "./Icons/MoreIcon.vue";
import { createLoader } from "@/util/loader";
import Loader from "./Loader.vue";

const posts = usePosts();
const users = useUsers();
const { post } = defineProps<{ post: IPost }>();

const user = ref<IUser | null>(null);
const loader = createLoader();

const gotoUser = () => {
  if (user.value !== null) router.push(`/user/${user.value.tag}`);
}

const like = (post: IPost | null) => {
  if (post !== null) posts.like(post);
}

const bookmark = (post: IPost | null) => {
  if (post !== null) posts.bookmark(post);
}

const deletePost = () => {
  if (post.userId !== users.current) return;
  if (post !== null) posts.delete(post);
}

const fetch = async () => {
  user.value = users.getUserById(post.userId);
  if (user.value !== null) return;
  await loader.value.wait(users.fetchUserById(post.userId));
  fetch();
}

fetch();
</script>

<template>
  <div v-if="!user || loader.status" class="post">
    <Loader />
  </div>
  <div v-else class="post">
    <div class="top">
      <div class="top-container">
        <span class="user-info" @click="gotoUser()">
          <span class="username dynamic">{{  user.name  }}</span>
          <span>@</span>
          <span class="usertag dynamic">{{  user.tag  }}</span>
        </span>
        <span class="date" :title="date.unix(post.date).format('lll')">
          {{  date.unix(post.date).fromNow()  }}
        </span>
      </div>
      <span>
        <MoreIcon class="icon more" @click="deletePost()" />
      </span>
    </div>
    <div class="mid">
      {{  post.content  }}
    </div>
    <div class="bottom">
      <span class="count">{{  post.likeCount  }}</span>
      <HeartIcon class="icon" :class="{ active: post.liked }" @click="like(post)" />
      <BookmarkIcon class="icon" :class="{ active: post.bookmarked }" @click="bookmark(post)" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.post {
  &:last-child {
    border-bottom: 0;
  }

  padding: 1rem 0;
  border-bottom: 1px solid #000000;
}

.top {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-between;
}

.mid {
  padding: 0 0 0.25rem 1rem;
  white-space: pre-wrap;
  word-break: break-word;
}

.bottom {
  display: flex;
  align-items: center;
  padding-left: 1rem;
}

.top-container {
  display: flex;
  flex-direction: row;
}

.user-info {
  cursor: pointer;

  display: grid;
  grid-template-columns: auto auto auto;

  .dynamic {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }

  &:hover {
    border-bottom: 1px solid #000000;
  }
}

.username {
  padding-right: 0.25rem;
}

.usertag {
  padding-right: 0.25rem;
}

.date {
  cursor: pointer;

  white-space: nowrap;

  &:hover {
    border-bottom: 1px solid #000000;
  }
}

.icon {
  cursor: pointer;

  &.active {
    fill: #000000;
  }

  &.more {
    position: relative;
    top: 0.125rem;
  }
}

.count {
  margin-right: 0.25rem;
}
</style>
