// frontend/src/components/User/index.tsx
import { CalendarToday } from "@styled-icons/material-rounded";
import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import styled from "styled-components"
import { IUser } from "../../../../shared/types";
import { useUserStore } from "../../store/userStore";
import UserEditProfile from "../UserEditProfile";
import Button from "../Util/Button";

const Wrapper = styled.div`
  padding: 1rem 0;
  border-bottom: 1px solid #000000;
`;

const Username = styled.div`
  font-size: ${props => props.theme.font.big}px;
  white-space: pre-wrap;
  word-break: break-word;
`;

const UsertagOuterWrapper = styled.div`
  display: flex;
  flex-direction: row;
`;

const UsertagInnerWrapper = styled.div`
  display: grid;
  grid-template-columns: auto auto auto;
  align-items: baseline;
`;

const UsertagHandle = styled.span`
  white-space: nowrap;
`;

const Usertag = styled.span`
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
`;

const FollowsYou = styled.span`
  border-bottom: 1px solid #000000;
  margin-left: 0.5rem;
  white-space: nowrap;
`;

const Bio = styled.div`
  padding-top: 0.5rem;
  white-space: pre-wrap;
  word-break: break-word;
`;

const DateWrapper = styled.div`
  display: flex;
  align-items: center;
  padding: 0.5rem 0;
`;

const Date = styled.div`
  margin-left: 0.25rem;
`;

const Bottom = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-direction: row;
  flex-wrap: wrap;
`;

const FollowWrapper = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  margin: 0.25rem 0;
`;

const Follow = styled.div`
  cursor: pointer;
  
  margin-right: 0.5rem;
  white-space: nowrap;

  &:hover {
    border-bottom: 1px solid #000000;
    margin-bottom: -1px;
  }
`;

function User({ user }: { user: IUser }) {
  const follow = useUserStore(state => state.followUser);
  const currentUser = useUserStore(state => state.getCurrentUser());

  const params = useParams();
  const navigate = useNavigate();

  const gotoFollowings = () => navigate(`/user/${params.tag}/followings`);
  const gotoFollowers = () => navigate(`/user/${params.tag}/followers`);
  const doFollow = () => follow(user)

  const [showEdit, setShowEdit] = useState(false);

  return (
    <Wrapper>
      {showEdit && <UserEditProfile user={user} show={showEdit} setShow={setShowEdit} />}
      <Username>{user.name}</Username>
      <UsertagOuterWrapper>
        <UsertagInnerWrapper>
          <UsertagHandle>@</UsertagHandle>
          <Usertag>{user.tag}</Usertag>
          {user.follower ? <FollowsYou>follows you</FollowsYou> : null}
        </UsertagInnerWrapper>
      </UsertagOuterWrapper>
      <Bio>{user.bio}</Bio>
      <DateWrapper>
        <CalendarToday size={32} />
        <Date>Aug 27, 2022</Date>
      </DateWrapper>
      <Bottom>
        <FollowWrapper>
          <Follow onClick={gotoFollowings}>{user.followingCount} followings</Follow>
          <Follow onClick={gotoFollowers}>{user.followerCount} followers</Follow>
        </FollowWrapper>
        {currentUser && currentUser.id !== user.id ? <Button size="big" onClick={doFollow}>{user.following ? "unfollow" : "follow"}</Button> : null}
        {currentUser && currentUser.id === user.id ? <Button size="big" onClick={() => void setShowEdit(!showEdit)}>edit profile</Button> : null}
      </Bottom>
    </Wrapper>
  )
}

export default User

// frontend/src/components/User.vue
<script setup lang="ts">
import router from "@/router";
import { useUsers } from "@/stores/users";
import { date } from "@/util/date";
import { nextTick, ref } from "vue";
import type { IUser } from "../../../shared/types";
import CalendarIcon from "./Icons/CalendarIcon.vue";
import Loader from "./Loader.vue";
import UserEditProfile from "./UserEditProfile.vue";
import Button from "./Button.vue";

const users = useUsers();
const { user, searching } = defineProps<{ user: IUser | null, searching: boolean }>();
const editingProfile = ref(false);

const follow = (user: IUser | null) => {
  if (user !== null) users.follow(user);
}

const gotoFollowers = (user: IUser | null) => {
  if (user !== null) router.push(`/user/${user.tag}/followers`)
}

const gotoFollowings = (user: IUser | null) => {
  if (user !== null) router.push(`/user/${user.tag}/followings`)
}

const editProfile = () => {
  editingProfile.value = false;
  nextTick(() => { editingProfile.value = true; })
}
</script>

<template>
  <UserEditProfile v-if="editingProfile && user" :editingProfile="editingProfile" :user="user" />
  <div v-if="!user && !searching" class="user">user not found</div>
  <div v-if="!user && searching" class="user">
    <Loader />
  </div>
  <div v-if="user" class="user">
    <div class="username">{{  user.name  }}</div>
    <div class="usertag">@{{  user.tag  }}</div>
    <div class="bio" v-show="user.bio.length > 0">{{  user.bio  }}</div>
    <div class="date">
      <CalendarIcon />
      <span>{{  date.unix(user.date).format('ll')  }}</span>
    </div>
    <div class="bottom">
      <span class="follow-container">
        <span class="followings" @click="gotoFollowings(user)">{{  user.followingCount  }} following</span>
        <span class="followers" @click="gotoFollowers(user)">{{  user.followerCount  }} followers</span>
      </span>
      <Button class="button" @click="follow(user)" v-if="user.id !== users.current">
        {{  user.following ? "unfollow" : "follow"  }}
      </Button>
      <Button class="button" @click="editProfile()" v-if="user.id === users.current">edit profile</Button>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.user {
  padding: 1rem 0;
  border-bottom: 1px solid #000000;
}

.username {
  font-size: $font-big;
  white-space: pre-wrap;
  word-break: break-word;
}

.usertag {
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}

.bio {
  padding-top: 0.5rem;
  white-space: pre-wrap;
  word-break: break-word;
}

.date {
  display: flex;
  align-items: center;
  padding: 0.5rem 0;
}

.bottom {
  display: flex;
  align-items: center;
  justify-content: space-between;

  .button {
    white-space: nowrap;
    padding: 0.5rem 1.25rem;
  }
}

.follow-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.followings {
  cursor: pointer;
  margin-right: 0.5rem;
  margin-bottom: 1px;
  white-space: nowrap;

  &:hover {
    border-bottom: 1px solid #000000;
    margin-bottom: 0;
  }
}

.followers {
  cursor: pointer;
  margin-bottom: 1px;
  white-space: nowrap;

  &:hover {
    border-bottom: 1px solid #000000;
    margin-bottom: 0;
  }
}
</style>
