// frontend/src/components/UserSummary/index.tsx
import { MouseEvent, useReducer } from "react";
import { useNavigate } from "react-router-dom";
import styled, { css } from "styled-components"
import { IUser } from "../../../../shared/types";
import Button from "../Util/Button";

const Wrapper = styled.div`
  cursor: pointer;

  padding: 1rem 0;
  border-bottom: 1px solid #000000;
  
  &:last-child {
    border-bottom: 0;
  }
`;

const UserInfoOuterWrapper = styled.div`
  display: flex;
  flex-direction: row;
`;

const UserInfoInnerWrapper = styled.div`
  display: grid;
  grid-template-columns: auto auto auto auto;
  align-items: baseline;
`;

const UsertagHandle = styled.span`
  white-space: nowrap;
`;

const overflowEllipsis = css`
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
`;

const Username = styled.span`
  ${overflowEllipsis}
  margin-right: 0.25rem;
`;

const Usertag = styled.span`
  ${overflowEllipsis}
  margin-right: 0.25rem;
`;

const FollowsYou = styled.span`
  border-bottom: 1px solid #000000;
  white-space: nowrap;
`;

const Bio = styled.div`
  padding: 0.5rem 0;
  white-space: pre-wrap;
  word-break: break-word;
`;

const Bottom = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-direction: row;
  flex-wrap: wrap;
`;

const FollowContainer = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  margin: 0.25rem 0;
`;

const Follow = styled.div`
  margin-right: 0.5rem;
  white-space: nowrap;
`;

function UserSummary({ user }: { user: IUser }) {
  const navigate = useNavigate();

  const gotoUser = () => {
    navigate("/user/aaa");
  }

  const follow = (ev: MouseEvent<HTMLButtonElement>) => {
    ev.stopPropagation();
  }

  return (
    <Wrapper onClick={gotoUser}>
      <UserInfoOuterWrapper>
        <UserInfoInnerWrapper>
          <Username>{user.name}</Username>
          <UsertagHandle>@</UsertagHandle>
          <Usertag>{user.tag}</Usertag>
          <FollowsYou>follows you</FollowsYou>
        </UserInfoInnerWrapper>
      </UserInfoOuterWrapper>
      <Bio>{user.bio}</Bio>
      <Bottom>
        <FollowContainer>
          <Follow>{user.followingCount} followings</Follow>
          <Follow>{user.followerCount} followers</Follow>
        </FollowContainer>
        <Button size="big" onClick={follow}>follow</Button>
      </Bottom>
    </Wrapper>
  )
}

export default UserSummary

// frontend/src/components/UserSummary.vue
<script setup lang="ts">
import router from "@/router";
import { useUsers } from "@/stores/users";
import { date } from "@/util/date";
import { createLoader } from "@/util/loader";
import type { IUser } from "../../../shared/types";
import CalendarIcon from "./Icons/CalendarIcon.vue";
import Loader from "./Loader.vue";
import Button from "./Button.vue";
import { i18n } from "@/util/i18n";

const users = useUsers();
const { t } = i18n.global;
const { user } = defineProps<{ user: IUser | null }>();

const follow = (user: IUser | null) => {
  if (user !== null) users.follow(user);
}

const gotoUser = (user: IUser | null) => {
  if (user !== null) router.push(`/user/${user.tag}`)
}
</script>

<template>
  <div v-if="!user" class="user-summary">
    <Loader />
  </div>
  <div v-else class="user-summary clickable" @click="gotoUser(user)">
    <span class="user-info-container">
      <span class="user-info">
        <span class="username dynamic">{{  user.name  }}</span>
        <span>@</span>
        <span class="usertag dynamic">{{  user.tag  }}</span>
        <span class="follows-you" v-if="user.follower">{{  t("follows_you")  }}</span>
      </span>
    </span>
    <div class="bio">{{  user.bio  }}</div>
    <div class="bottom">
      <span class="follow-container">
        <span class="followings">
          {{  `${user.followingCount} ${t("following_count", user.followingCount)}`  }}
        </span>
        <span class="followers">
          {{  `${user.followerCount} ${t("follower_count", user.followerCount)}`  }}
        </span>
      </span>
      <Button class="follow-button" @click.stop="follow(user)" v-if="user.id !== users.current">
        {{  user.following ? t("unfollow") : t("follow")  }}
      </Button>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.user-summary {
  padding: 1rem 0;
  border-bottom: 1px solid #000000;

  &.clickable {
    cursor: pointer;
  }
}

.user-info-container {
  display: flex;
  flex-direction: row;
}

.user-info {
  display: grid;
  grid-template-columns: auto auto auto auto;
  align-items: baseline;

  .dynamic {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }
}

.username {
  font-size: $font-big;
  white-space: pre;
  padding-right: 0.25rem;
}

.usertag {
  padding-right: 0.25rem;
}

.follows-you {
  border-bottom: 1px solid #000000;
}

.bio {
  padding: 0.5rem 0;
  white-space: pre-wrap;
  word-break: break-word;
}

.bottom {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.follow-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
}

.followings {
  margin-right: 0.25rem;
  white-space: nowrap;
}

.followers {
  margin-left: 0.25rem;
  white-space: nowrap;
}

.follow-button {
  padding: 0.5rem 1.25rem;
}
</style>
