// frontend_vue/src/components/Bar/TopBar.vue
<script lang="ts" setup>
import MenuIcon from "../Icons/MenuIcon.vue";
import BackIcon from "../Icons/BackIcon.vue";
import router from "@/router";
import { i18n } from "@/util/i18n";
import { useApp } from "@/stores/app";

const { t } = i18n.global;
const app = useApp();

const toggleMenu = () => {
  if (router.currentRoute.value.meta.menuType) router.push(app.routeBeforeMenu);
  else router.push("/menu");
}
</script>

<template>
  <div>
    <div class="container">
      <div class="content">
        <span class="right">
          <BackIcon class="icon right" @click="router.back()" v-if="router.currentRoute.value.meta.showBackButton" />
          <span v-if="router.currentRoute.value.name" class="title">{{
             t(router.currentRoute.value.name.toString())  }}</span>
        </span>
        <MenuIcon class="icon" @click="toggleMenu()" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.container {
  height: 3rem;

  position: fixed;
  top: 0;
  left: 0;
  right: 0;

  background-color: #ffffff;
  border-bottom: 1px solid #000000;

  z-index: 999;
}

.content {
  max-width: 640px;
  height: inherit;

  margin: 0 auto;

  display: flex;
  align-items: center;
  justify-content: space-between;
}

.right {
  display: flex;
  align-items: center;
}

.title {
  font-size: $font-big;
  margin-left: 3rem;
}

.icon {
  box-sizing: content-box;
  cursor: pointer;
  padding: 0.5rem;

  &.right {
    position: absolute;
  }
}
</style>

// frontend/src/components/Bar/TopBar.tsx
import { ArrowBack, Menu } from "@styled-icons/material-rounded";
import { useTranslation } from "react-i18next";
import { useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import styled, { css } from "styled-components"
import { RootState } from "../../store/store";
import { Icon } from "../../style/styled";
import { InnerContainer, OuterContainer } from "./style"

const RightWrapper = styled.div`
  display: flex;
  align-items: center;
`;

const LeftWrapper = styled.div`

`;

const Title = styled.span<{ margin: boolean }>`
  ${props => props.margin ? css` margin-left: 1rem;` : ""}
  font-size: ${props => props.theme.font.big}px;
`;

function TopBar() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const route = useSelector((state: RootState) => state.app.routeProperties);

  const goBack = () => {
    navigate(-1);
  }

  const toggleMenu = () => {
    if (route.name !== "menu") navigate("/menu");
    else if (route.routeBeforeMenu) navigate(route.routeBeforeMenu);
  }

  return (
    <OuterContainer type="top">
      <InnerContainer type="top">
        <RightWrapper>
          {route.showBackButton ? <Icon as={ArrowBack} onClick={goBack} /> : ""}
          <Title margin={!route.showBackButton}>{t(route.name as any)}</Title>
        </RightWrapper>
        <LeftWrapper>
          <Icon as={Menu} onClick={toggleMenu} />
        </LeftWrapper>
      </InnerContainer>
    </OuterContainer>
  )
}

export default TopBar
